### PR TITLE
Array comprehensions e2e tests

### PR DESCRIPTION
**Pull request by ggawryal**
Since parser changes aren't done yet (if I'm not mistaken), it is likely that there are some discrepancies between the actual syntax and the one in the tests and outputs might not be always correct, so feel free to decide if you want to review it now or after we review another PRs.

### CODE REVIEW

**Review by tomekb234 — DISMISSED** [review]

**Comment by tomekb234** [comment]
The `.test` files should have extension `.tests`.

**Comment by tomekb234** [comment]
Please merge `arrays-comprehension-up-to-ast` and resolve the syntax errors.

Some remarks:
- Due to the limitations of the grammar, it seems that we can't have a closing parenthesis `)` on the new line.
- Because of implementation problems in #179, we changed the syntax from `ciąg (x dla x: Liczba wewnątrz a)` to unfortunately more cumbersome `ciąg (x (dla x: Liczba wewnątrz a))`.
- Name resolution doesn't work with nested array comprehensions, but it can be replaced with multiple sources.

See the discussion under #179.

**Comment by ggawryal** [comment]
The following code causes RTE, I'm gonna investigate reference counting for this
```
czynność f(c_nieważne: [Liczba]) -> [Liczba] {
    zwróć ciąg Liczba {1}
}

czynność główna() {
    zm x : [Liczba] = ciąg Liczba {1}
    napisz(długość f(x));
}
```

Also, expression parsing is incorrect: `4*100+3*10+2` is parsed as `(4*100+3)*10+2`, but we can temporarily mitigate this in tests and create a separate issue.

**Review by tomekb234 — APPROVED** [review]

**Comment by JHodorHodor** [comment]
I added an [issue](https://github.com/TCS-Compilers/compiler/issues/185#issue-1554544620) for the clumsy syntax with parenthesis.

Also, I [fixed](https://github.com/TCS-Compilers/compiler/pull/183#issue-1554537346) the "nesting" issue a little, however, there are still some problems in the later stages.

**Pull request merged**
